package com.example.quanlykho.view;// Generated by Selenium IDE
import org.junit.After;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.BeforeEach;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.interactions.Actions;

import java.util.*;

public class TestThanhToan {
  private WebDriver driver;

  @BeforeEach
  public void setUp() throws InterruptedException {
    System.setProperty("webdriver.chrome.driver", "/Users/maccuacu/Downloads/chromedriver_mac/chromedriver");
    ChromeOptions options = new ChromeOptions();
    driver = new ChromeDriver(options);
    driver.get("http://localhost:9091/");
    Thread.sleep(5000);
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testThanhToan01() {
    // Test name: TestThanhToan01
    // Step # | name | target | value | comment
    // 1 | open | / |  | 
    driver.get("http://localhost:9091/");
    // 2 | setWindowSize | 1680x982 |  | 
    driver.manage().window().setSize(new Dimension(1680, 982));
    // 3 | click | css=.bi-cart |  | 
    driver.findElement(By.cssSelector(".bi-cart")).click();
    // 4 | click | css=.row:nth-child(5) form |  | 
    driver.findElement(By.cssSelector(".row:nth-child(5) form")).click();
    // 5 | mouseOver | css=.row:nth-child(3) .btn:nth-child(5) > .fas |  | 
    {
      WebElement element = driver.findElement(By.cssSelector(".row:nth-child(3) .btn:nth-child(5) > .fas"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 6 | click | css=.ripple-surface > .fas |  | 
    driver.findElement(By.cssSelector(".ripple-surface > .fas")).click();
    // 7 | click | css=.btn-dark |  | 
    driver.findElement(By.cssSelector(".btn-dark")).click();
    // 8 | click | css=.btn |  | 
    driver.findElement(By.cssSelector(".btn")).click();
  }
}
