// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestAddManyProductIntoCartTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testAddManyProductIntoCart() {
    // Test name: TestAddManyProductIntoCart
    // Step # | name | target | value | comment
    // 1 | open | / |  | 
    driver.get("http://localhost:9091/");
    // 2 | setWindowSize | 1680x982 |  | 
    driver.manage().window().setSize(new Dimension(1680, 982));
    // 3 | click | css=.nav-item:nth-child(2) |  | 
    driver.findElement(By.cssSelector(".nav-item:nth-child(2)")).click();
    // 4 | click | linkText=Thêm vào giỏ hàng |  | 
    driver.findElement(By.linkText("Thêm vào giỏ hàng")).click();
    // 5 | click | css=.col-lg-8 > .p-5 |  | 
    driver.findElement(By.cssSelector(".col-lg-8 > .p-5")).click();
    // 6 | click | css=.col-lg-8 > .p-5 |  | 
    driver.findElement(By.cssSelector(".col-lg-8 > .p-5")).click();
    // 7 | doubleClick | css=.col-lg-8 > .p-5 |  | 
    {
      WebElement element = driver.findElement(By.cssSelector(".col-lg-8 > .p-5"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    // 8 | click | linkText=Quay lại shop |  | 
    driver.findElement(By.linkText("Quay lại shop")).click();
    // 9 | click | linkText=Thêm vào giỏ hàng |  | 
    driver.findElement(By.linkText("Thêm vào giỏ hàng")).click();
    // 10 | click | linkText=Quay lại shop |  | 
    driver.findElement(By.linkText("Quay lại shop")).click();
    // 11 | click | linkText=Thêm vào giỏ hàng |  | 
    driver.findElement(By.linkText("Thêm vào giỏ hàng")).click();
    // 12 | click | linkText=Quay lại shop |  | 
    driver.findElement(By.linkText("Quay lại shop")).click();
    // 13 | click | linkText=Thêm vào giỏ hàng |  | 
    driver.findElement(By.linkText("Thêm vào giỏ hàng")).click();
    // 14 | mouseOver | css=.row:nth-child(3) .btn:nth-child(5) |  | 
    {
      WebElement element = driver.findElement(By.cssSelector(".row:nth-child(3) .btn:nth-child(5)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 15 | click | css=.ripple-surface |  | 
    driver.findElement(By.cssSelector(".ripple-surface")).click();
  }
}
