package com.example.quanlykho.view;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestCreateProduct02Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testCreateProduct02() {
    // Test name: TestCreateProduct02
    // Step # | name | target | value | comment
    // 1 | open | /ShowProductsServlet |  | 
    driver.get("http://localhost:9091/ShowProductsServlet");
    // 2 | setWindowSize | 1680x982 |  | 
    driver.manage().window().setSize(new Dimension(1680, 982));
    // 3 | click | linkText=Thêm mới |  | 
    driver.findElement(By.linkText("Thêm mới")).click();
    // 4 | click | name=prCode |  | 
    driver.findElement(By.name("prCode")).click();
    // 5 | type | name=prCode | TPTS05 | 
    driver.findElement(By.name("prCode")).sendKeys("TPTS05");
    // 6 | click | name=prName |  | 
    driver.findElement(By.name("prName")).click();
    // 7 | type | name=prName | cà  | 
    driver.findElement(By.name("prName")).sendKeys("cà ");
    // 8 | click | name=prPrice |  | 
    driver.findElement(By.name("prPrice")).click();
    // 9 | type | name=prPrice | 4000 | 
    driver.findElement(By.name("prPrice")).sendKeys("4000");
    // 10 | click | css=.text-dark:nth-child(9) |  | 
    driver.findElement(By.cssSelector(".text-dark:nth-child(9)")).click();
    // 11 | click | name=prQuantity |  | 
    driver.findElement(By.name("prQuantity")).click();
    // 12 | type | name=prQuantity | 100 | 
    driver.findElement(By.name("prQuantity")).sendKeys("100");
    // 13 | click | name=prImg |  | 
    driver.findElement(By.name("prImg")).click();
    // 14 | type | name=prImg | https://vinmec-prod.s3.amazonaws.com/images/20190606_120002_041483_ca-rot.max-800x800.png | 
    driver.findElement(By.name("prImg")).sendKeys("https://vinmec-prod.s3.amazonaws.com/images/20190606_120002_041483_ca-rot.max-800x800.png");
    // 15 | click | css=#createModal .modal-body |  | 
    driver.findElement(By.cssSelector("#createModal .modal-body")).click();
    // 16 | click | name=prDateInput |  | 
    driver.findElement(By.name("prDateInput")).click();
    // 17 | type | name=prDateInput | 2023-11-03 | 
    driver.findElement(By.name("prDateInput")).sendKeys("2023-11-03");
    // 18 | click | name=prDetail |  | 
    driver.findElement(By.name("prDetail")).click();
    // 19 | type | name=prDetail | h | 
    driver.findElement(By.name("prDetail")).sendKeys("h");
    // 20 | click | id=addProductBtn |  | 
    driver.findElement(By.id("addProductBtn")).click();
    // 21 | click | css=.alert span |  | 
    driver.findElement(By.cssSelector(".alert span")).click();
  }
}
