package com.example.quanlykho.view;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;

public class TestLogin01Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testLogin01() {
    driver.get("http://localhost:9091/");
    driver.manage().window().setSize(new Dimension(1680, 982));
    driver.findElement(By.linkText("Đăng nhập")).click();
    driver.findElement(By.id("admin")).click();
    driver.findElement(By.id("admin")).click();
    driver.findElement(By.cssSelector(".btn")).click();
  }
}
