package com.example.quanlykho.view;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestCreateProduct01Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testCreateProduct01() {
    // Test name: TestCreateProduct01
    // Step # | name | target | value | comment
    // 1 | open | / |  | 
    driver.get("http://localhost:9091/");
    // 2 | setWindowSize | 1680x982 |  | 
    driver.manage().window().setSize(new Dimension(1680, 982));
    // 3 | click | linkText=Logout |  | 
    driver.findElement(By.linkText("Logout")).click();
    // 4 | click | id=form2Example18 |  | 
    driver.findElement(By.id("form2Example18")).click();
    // 5 | type | id=form2Example18 | admin | 
    driver.findElement(By.id("form2Example18")).sendKeys("admin");
    // 6 | click | id=form2Example28 |  | 
    driver.findElement(By.id("form2Example28")).click();
    // 7 | click | id=form2Example28 |  | 
    driver.findElement(By.id("form2Example28")).click();
    // 8 | mouseOver | css=.btn |  | 
    {
      WebElement element = driver.findElement(By.cssSelector(".btn"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 9 | type | id=form2Example28 | admin | 
    driver.findElement(By.id("form2Example28")).sendKeys("admin");
    // 10 | click | css=.btn |  | 
    driver.findElement(By.cssSelector(".btn")).click();
    // 11 | click | linkText=Thêm mới |  | 
    driver.findElement(By.linkText("Thêm mới")).click();
    // 12 | click | name=prCode |  | 
    driver.findElement(By.name("prCode")).click();
    // 13 | click | name=prCode |  | 
    driver.findElement(By.name("prCode")).click();
    // 14 | click | name=prCode |  | 
    driver.findElement(By.name("prCode")).click();
    // 15 | doubleClick | name=prCode |  | 
    {
      WebElement element = driver.findElement(By.name("prCode"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    // 16 | type | name=prCode | test01 | 
    driver.findElement(By.name("prCode")).sendKeys("test01");
    // 17 | click | name=prName |  | 
    driver.findElement(By.name("prName")).click();
    // 18 | type | name=prName | test01 | 
    driver.findElement(By.name("prName")).sendKeys("test01");
    // 19 | click | name=prPrice |  | 
    driver.findElement(By.name("prPrice")).click();
    // 20 | type | name=prPrice | 99999 | 
    driver.findElement(By.name("prPrice")).sendKeys("99999");
    // 21 | click | name=prQuantity |  | 
    driver.findElement(By.name("prQuantity")).click();
    // 22 | type | name=prQuantity | 100 | 
    driver.findElement(By.name("prQuantity")).sendKeys("100");
    // 23 | click | name=prImg |  | 
    driver.findElement(By.name("prImg")).click();
    // 24 | click | name=prImg |  | 
    driver.findElement(By.name("prImg")).click();
    // 25 | type | name=prImg | https://cdn.tgdd.vn/2021/01/content/bo%CC%80vai-800x500.jpg | 
    driver.findElement(By.name("prImg")).sendKeys("https://cdn.tgdd.vn/2021/01/content/bo%CC%80vai-800x500.jpg");
    // 26 | click | name=prDateInput |  | 
    driver.findElement(By.name("prDateInput")).click();
    // 27 | type | name=prDateInput | 2023-11-18 | 
    driver.findElement(By.name("prDateInput")).sendKeys("2023-11-18");
    // 28 | click | name=prDetail |  | 
    driver.findElement(By.name("prDetail")).click();
    // 29 | type | name=prDetail | test01 | 
    driver.findElement(By.name("prDetail")).sendKeys("test01");
    // 30 | click | id=addProductBtn |  | 
    driver.findElement(By.id("addProductBtn")).click();
    // 31 | click | css=.alert span |  | 
    driver.findElement(By.cssSelector(".alert span")).click();
  }
}
