package com.example.quanlykho.view;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestDeleteProduct01Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testDeleteProduct01() {
    // Test name: TestDeleteProduct01
    // Step # | name | target | value | comment
    // 1 | open | /ShowProductsServlet |  | 
    driver.get("http://localhost:9091/ShowProductsServlet");
    // 2 | setWindowSize | 1680x982 |  | 
    driver.manage().window().setSize(new Dimension(1680, 982));
    // 3 | click | css=.odd:nth-child(1) > td > .btn-danger |  | 
    driver.findElement(By.cssSelector(".odd:nth-child(1) > td > .btn-danger")).click();
    // 4 | click | linkText=Xoá |  | 
    driver.findElement(By.linkText("Xoá")).click();
    // 5 | runScript | window.scrollTo(0,111) |  | 
    js.executeScript("window.scrollTo(0,111)");
  }
}
