// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestSapXeptheoMATest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testSapXeptheoMA() {
    // Test name: TestSapXeptheoMA
    // Step # | name | target | value | comment
    // 1 | open | /ShowProductsServlet |  | 
    driver.get("http://localhost:9091/ShowProductsServlet");
    // 2 | setWindowSize | 1680x982 |  | 
    driver.manage().window().setSize(new Dimension(1680, 982));
    // 3 | click | css=.sorting_asc |  | 
    driver.findElement(By.cssSelector(".sorting_asc")).click();
    // 4 | click | css=.sorting_desc |  | 
    driver.findElement(By.cssSelector(".sorting_desc")).click();
    // 5 | click | css=.sorting_asc |  | 
    driver.findElement(By.cssSelector(".sorting_asc")).click();
    // 6 | click | css=.sorting_desc |  | 
    driver.findElement(By.cssSelector(".sorting_desc")).click();
    // 7 | doubleClick | css=.sorting_asc |  | 
    {
      WebElement element = driver.findElement(By.cssSelector(".sorting_asc"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    // 8 | click | css=.img-profile |  | 
    driver.findElement(By.cssSelector(".img-profile")).click();
    // 9 | click | linkText=Đăng xuất |  | 
    driver.findElement(By.linkText("Đăng xuất")).click();
    // 10 | click | linkText=Đăng xuất |  | 
    driver.findElement(By.linkText("Đăng xuất")).click();
    // 11 | close |  |  | 
    driver.close();
  }
}
